---

- hosts: all
  become: true
  tasks:

 
  - name: Install apache package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Centos" 
  
  - name: Install vim pachage
    yum:
      name: vim
      state: latest
    when: ansible_distribution == "Centos" 
        
