---

- hosts: all
  become: true
  tasks:

 
  - name: Install apache package
    yum:
      name: httpd
      state: latest
  
  - name: Install vim pachage
    yum:
      name: vim
      state: latest
        
