---

- hosts: all
  become: true
  pre_tasks:

   - name: Install updates CentOS
     yum:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"

   - name: Install updates Ubuntu
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"      


- hosts: backup
  become: true
  tasks:
   - name: Install apache vim package
     apt:
       name: 
         - httpd
         - vim
       state: latest
     when: ansible_distribution == "Ubuntu"

- hosts: main
  become: true
  tasks:
   - name: Install apache vim package
     yum:
       name: 
         - httpd
         - vim
       state: latest
     when: ansible_distribution == "CentOS"

         
- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb packagw CentOS
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb packagw CentOS
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
 
- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    package:
      name: samba
      state: latest
